### ISSUE TITLE
【Bug】快速点击“确认键”会重复添加 裁剪后的图片

### ISSUE THREAD

**Issue by koibi2** [cmqiong/vue-upload-cropper#1]
详情见gif图片→

![vue](https://user-images.githubusercontent.com/34370367/41626891-927a6192-7450-11e8-836f-0789e964b398.gif)

**Comment by cmqiong** [comment]
谢谢你提的 bug，我会尽快修复

**Comment by cmqiong** [comment]
@koibi2 v1.0.4 已修复

**Comment by koibi2** [comment]
效率好高，辛苦了！
